### ISSUE TITLE
3.13.4 (beta build) fails to start on OS X 10.8.5

### ISSUE THREAD

**Issue by 1-61803** [yousseb/meld#4]
Console logs  
`30.1.16 2:49:16.205 PM com.apple.launchd.peruser.501[242]: ([0x0-0xa8ba8b].org.gnome.meld[53298]) Exited with code: 1`

**Comment by Pauldic** [comment]
Same issue on OSX 10.11.3

**Comment by 1-61803** [comment]
If I run the binary I get this
	$ /Users/test/Desktop/Meld.app/Contents/MacOS/Meld 
	/Users/test/Desktop/Meld.app/Contents/Resources/lib:/Users/test/Desktop/Meld.app/Contents/Frameworks
	Couldn't bind the translation domain. Some translations won't work.
	'module' object has no attribute 'bind_textdomain_codeset'
	Cannot import: GTK+
	cannot import name Gtk

**Comment by yousseb** [comment]
The translation part is OK. But it's odd that it can't import GTK+
I'll look into it. Thanks for the report.

**Comment by william-voyek** [comment]
I have the same issue:
```
$ sw_vers; /Applications/Meld.app/Contents/MacOS/Meld
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F1605
/Applications/Meld.app/Contents/Resources/lib:/Applications/Meld.app/Contents/Frameworks
Couldn't bind the translation domain. Some translations won't work.
'module' object has no attribute 'bind_textdomain_codeset'
Cannot import: GTK+
cannot import name Gtk
```

**Comment by mgraff** [comment]
Hi,
Same issue here.

After some digging, I found that libraries seems linked with wrong paths.
Eg.:
```
/Applications/Meld.app/Contents/Resources/lib/gtk-3.0/3.0.0/immodules/im-cedilla.so:
    /Users/yousseb/gtk/inst/lib/libgtk-3.0.dylib (compatibility version 1601.0.0, current version 1601.0.0)
    /Users/yousseb/gtk/inst/lib/libgdk-3.0.dylib (compatibility version 1601.0.0, current version 1601.0.0)
    /Users/yousseb/gtk/inst/lib/libgmodule-2.0.0.dylib (compatibility version 4401.0.0, current version 4401.1.0)
```

**Comment by yousseb** [comment]
Thanks, mgraff. This is awesome. I'll see how I can fix this.

**Comment by 1-61803** [comment]
And while you're at it, maybe you can update `meld`'s MacPorts port, which is still at 1.8.6. What do you think?

**Comment by yousseb** [comment]
@1-61803 I don't have that much time, unfortunately..

**Comment by mgraff** [comment]
@yousseb Could you post the detailed build procedure that you currently follow.
Maybe I can spend some time trying fixing it.

**Comment by 1-61803** [comment]
@yousseb, actually I thought a MacPort's port might be easier.

**Comment by yousseb** [comment]
It probably is. But I can't get retina clean UI and fonts on MacPorts. I'm working on getting this fixed within a couple of days. :)

**Comment by yousseb** [comment]
Can you guys try the latest release and let me know if it works?

**Comment by dguo** [comment]
:+1: Works for me on OS X 10.11.2

Thank you!

**Comment by dguo** [comment]
Actually, it looks like `Meld-bin` still produces the error that @1-61803  posted earlier. But the app itself opens and works fine.

```bash
$ /Applications/Meld.app/Contents/MacOS/Meld-bin
Couldn't bind the translation domain. Some translations won't work.
'module' object has no attribute 'bind_textdomain_codeset'
Cannot import: GTK+
cannot import name Gtk
```

**Comment by yousseb** [comment]
Thanks for the confirmation. 
You can't really run Meld-bin directly.. Meld bash script sets a load of required environment variable.  You should run /Applications/Meld.app/Contents/MacOS/Meld instead or /Applications/Meld.app/Contents/MacOS/Meld-bin

**Comment by dguo** [comment]
Ah, okay. I was trying to set it up with `git difftool`.

**Comment by yousseb** [comment]
Try this:
```
[diff]
        tool = meld
[difftool]
        prompt = false
[difftool "meld"]
        trustExitCode = true
        cmd = /Applications/Meld.app/Contents/MacOS/Meld \"$LOCAL\" \"$PWD/$REMOTE\"
```

**Comment by dguo** [comment]
That works. I was missing the arguments to `cmd`.

Thanks a lot for making this. I'm glad to be rid of the fuzzy text.

**Comment by 1-61803** [comment]
@yousseb, it works on OS X 10.8.5, thanks!
2 things though, window resizing it's quite tricky, and can you add full screen support?

**Comment by yousseb** [comment]
@1-61803 Thanks for the confirmation. 
Please open separate issues for those items. I'll close this thread as fixed for now..

**Comment by 1-61803** [comment]
Np, I opened #5. Window resizing seems to be not a problem anymore. I think it was when trying Meld in a VM.

**Comment by yousseb** [comment]
Thanks :)

**Comment by yousseb** [comment]
@mgraff Sorry didn't notice the question about the detailed build procedure. It's written step-by-step in the README.md file located here: https://github.com/yousseb/meld/blob/master/osx/README.md
